выполняю задание 2
Kolesa-Education/kolesa-upgrade-homework-3 pull request #26
Opened 2022-09-25 03:25 UTC by hAckeeVo

2022-09-25 08:00 UTC, lesmiras requested changes
Общие комменты:
1) Старайся типизировать все аргументы и возвращаемый результат методов.
2) Логику можно разделить на отдельные файлы для повышения расширяемости и удобности в будущем.
3) Отдельный класс для работы с API, отдельные объекты для работы с категорией и изображением. 

Нравиться что ты сделал вывод списка категорий. 
Попробуй развить это дальше и сделать категорий кликабельными. Кликается категория и делается поиск изображений из этой категорий. И нужно отмечать выбранную категорию. 

Еще в идеале, объекты нужно выводить через цикл в самом шаблоне.
Что нибудь, как
```
foreach($pictures as $picture) {
    echo $picture->render();
}
```
Попробуй разделить шабллонизацию отдельной реализацией. Ну или хотя бы каким нибудь удобными методами.

2022-09-25 08:00 UTC, lesmiras commented on Service.php
> +    public function serviceInitialization() {
вместо метода serviceInitialization можно использовать конструктор, чтобы при вызове класса Service формировался client без дополнительного вызова метода serviceInitialization().

2022-09-25 08:00 UTC, lesmiras commented on index.php
> +require_once $autoloadPath;
можно в одну строку `require_once __DIR__ . '/vendor/autoload.php';`

2022-09-25 08:00 UTC, lesmiras commented on Service.php
> +                echo '<img src="' . $array[0]['url'] . '" width="800" height="600"/>';
Думаю width="800" height="600" тут лишние, так как рандомно у фотографии разные размеры. 
А сейчас почти все выводятся они очень растянуто.

2022-09-25 08:00 UTC, lesmiras commented on Service.php
> +    public function getCategory() {
Если метод возврвщает какое множество, то и именовать стоит так же, чтобы было понятно что оно возвращает.
getCategories()

2022-09-25 08:00 UTC, lesmiras commented on Service.php
> +        $category = $_GET['category_ids'] ?? null;
если `category_ids` принимает только 1 идентификатор, то именовать проста `category_id`

2022-09-25 08:00 UTC, lesmiras commented on index.php
> +$catService = new Service();
У меня не получилось запустить, выводилось ошибка что не найден файл Service(). 
Пришлось править composer.json файл чтобы запустилось. 
Глянь пожалуйста все ли корректно рабтает без правок.

2022-09-25 08:00 UTC, lesmiras commented on Service.php
> +        $category = $_GET['category_ids'] ?? null;
Лучше чтобы идентификатор категории приходил из аргумента метода. 
Это даст гибкость для использования других хранилищ. 
Код в само методе не меняется и источник можно будет использовать другой.

2022-09-27 10:55 UTC, hAckeeVo commented on Service.php
> +    public function serviceInitialization() {
сделал

2022-09-27 10:55 UTC, hAckeeVo commented on index.php
> +require_once $autoloadPath;
сделал

2022-09-27 10:55 UTC, hAckeeVo commented on Service.php
> +                echo '<img src="' . $array[0]['url'] . '" width="800" height="600"/>';
убрал

2022-09-27 10:55 UTC, hAckeeVo commented on Service.php
> +    public function getCategory() {
переименовал

2022-09-27 10:55 UTC, hAckeeVo commented on Service.php
> +        $category = $_GET['category_ids'] ?? null;
это из адресной строки получаем, кажется так и должно быть :)

2022-09-27 10:56 UTC, hAckeeVo commented on index.php
> +$catService = new Service();
всё работает, могу видео записать, только заметил при первом пуше уведомление от Git, что какой-то файл будет изменён, подумал что это правильно

2022-09-27 10:56 UTC, hAckeeVo commented on Service.php
> +        $category = $_GET['category_ids'] ?? null;
сделал

2022-09-27 11:03 UTC, hAckeeVo commented
Сделал категории кликабельными, вывел название категории, но вот при разделении на файлы/классы получил много ошибок, не понял пока что делаю не так, кажется ошибка где-то между глаз, пришлось быстренько откатиться и сделать то, что получилось, у меня к сожалению катастрофиечски не хватает времени, хотя прохождение курса у меня в приоритете, номер 0 в списке TODO листа, и кстати я пока почему-то не могу сразу всё на PHP писать, я делаю наброски на Java и дальше перевожу уже, хотелось здесь реализовать классы ClientModel, ClientRequest, ClientResponse, сервис сделать интерфейсом, но у меня мало знаний по PHP, даже один Service не получилось разбить(

2022-09-27 12:44 UTC, lesmiras approved these changes

2022-09-28 06:34 UTC, closed without merging