выполняю задание 1
Kolesa-Education/kolesa-upgrade-homework-3 pull request #33
Opened 2022-09-25 10:30 UTC by olzhasmukayev

2022-09-25 13:12 UTC, lesmiras requested changes
Общие комменты:
1) Попробуй разделить все на отдельные файлы и классы. 
Класс клиент для работы с API, классы для категории и изображений.
Добавить ООП)) 
2) Оформить все с namespace-ами и autoloader-ом.
3) МОжет еще отдельную шаблонизацию, хотя бы ка какие нибудь удобные методы для вывода картинок.
4) Не забудь про типизацию аргументов и возвращаемого результата методов.

2022-09-25 13:12 UTC, lesmiras commented on index.php
> +    }
Хорошая идея проверить доступность сервиса. 
Но тут, как мне кажется, оно лишнее. Это не гарантирует что последующие запросы будут успешными. 
Нужно обрабатывать и отлавливать ошибки при каждом запросе в сторонние сервисы.

2022-09-25 13:12 UTC, lesmiras commented on index.php
> +            background-image: url("<?=$firstCat[0]["url"]?>");
Идея хорошая, но выглядит больше как костыль) 
Сделай лучше через тег img. 
И через стили можно оформить изображения.

2022-09-25 13:12 UTC, lesmiras commented on index.php
> +    $categoryId = 0;
Ок, вижу что ты попробовал 3 варианта получения картинки. Круто! 
Но лучше всего все запросы делать через один инструмент. Guzzle клиентом будет удобнее.

2022-09-26 13:30 UTC, lesmiras approved these changes

2022-09-26 13:30 UTC, lesmiras commented on index.php
> +            require 'vendor/autoload.php';
раз внедрил composer и autloader
тут такое уже не нужно)

2022-09-26 13:30 UTC, lesmiras commented on index.php
> +                        ?><div class="card first" style="background-image: url('<?php echo $loadImages->getImage($value)[0]["url"]; ?>')"></div><?php
вообще, по требованию нужно именно тег img заполненный с src атрибутом

2022-09-26 13:30 UTC, lesmiras commented on index.php
> +                    $categories = array("boxes", "kittens", "dream", "caturday", "clothes", "funny", "hats", "sunglasses", "ties", "caturday");
список категорий лучше получить из API
то есть,
1) сделать запрос на получения всех категорий из api
2) вывести результат

и будет у тебя всегда актуальный список категорий

2022-09-26 13:30 UTC, lesmiras commented on index.php
> +        }
Метод вышел сложноватый. 
Сперва делает checkStatus, потом делает запрос на получения категорий, и после еще получается картинку. 

1) убрать checkStatus()
2) получение категорий вынести в отдельную метода
а еще лучше сделать получения списка категорий и вывести отдельно
и в методе getImage принимать в аргументах id категорий
3) сделать запрос на получение картинки по указанной категории

2022-09-27 03:10 UTC, olzhasmukayev commented on index.php
> +                        ?><div class="card first" style="background-image: url('<?php echo $loadImages->getImage($value)[0]["url"]; ?>')"></div><?php
с teg-ом img, что то верстка получилось не очень(

а так, я пробовал с img, и сработало. Проблема была в заполнении картинкой всего div-a из за разных размеров изображений

2022-09-27 12:40 UTC, closed without merging