выполняю задание 3
Kolesa-Education/kolesa-upgrade-homework-3 pull request #4
Opened 2022-09-22 15:30 UTC by FishSev

третье ДЗ на ревью

2022-09-23 05:40 UTC, Tazya requested changes

2022-09-23 05:40 UTC, Tazya commented on src/index.php
> +<!DOCTYPE html>
Рекомендую все файлы, которые смотрят наружу, вынести в отдельную папку или в корень. Так разделим исполняемые файлы, от файлов только с кодом.

Рекомендую так-же не держать в index никакую логику вообще, только инициализации и вызовы классов, методов и функций.

Архитектуру приложений будем обсуждать ещё дальше, это первый шаг в её построении.

2022-09-23 05:40 UTC, Tazya commented on src/getPic.php
> +require_once $autoloadPath;
Попробуй использовать для получения и обработки изображения класс и неймспейс. Тогда не понадобится использовать здесь require_once, а только в index.php

2022-09-23 05:40 UTC, Tazya commented on src/getPic.php
> +    $client = new Client([
Если Было бы неплохо разбить на разные функции/методы
1. Инициализация объекта клиента Guzzle
2. Получение изображения со всеми манипуляциями над $response
3. Вывод готового результата (здесь ловить исключение)

2022-09-23 05:43 UTC, Tazya commented
И ещё - я как пользователь, не совсем понимаю какие категории какие результаты выведут) Хорошо бы их небольшой список вывести

2022-09-23 10:17 UTC, FishSev commented on src/index.php
> +<!DOCTYPE html>
Отработал архитектуру

2022-09-23 10:18 UTC, FishSev commented on src/getPic.php
> +require_once $autoloadPath;
Сделал

2022-09-23 10:18 UTC, FishSev commented on src/getPic.php
> +    $client = new Client([
Реализовал

2022-09-23 10:19 UTC, FishSev commented
> И ещё - я как пользователь, не совсем понимаю какие категории какие результаты выведут) Хорошо бы их небольшой список вывести

Тоже сделал)

2022-09-23 11:28 UTC, Tazya requested changes

2022-09-23 11:28 UTC, Tazya commented on index.php
> +require_once 'src\CatPictureService.php';
Не разобрался с автозагрузкой.
Не нужен `require_once 'src\CatPictureService.php';`, если ты правильно указал неймспейс. Можно смело удалять

Обрати внимание на composer.json, там у тебя алиас некорректный.

2022-09-23 11:28 UTC, Tazya commented on src/CatPictureService.php
> +// EOF
EOF, это зачем?

2022-09-23 11:46 UTC, FishSev commented on index.php
> +require_once 'src\CatPictureService.php';
Сделал, спасибо

2022-09-23 11:46 UTC, FishSev commented on src/CatPictureService.php
> +// EOF
Просто, где-то увидел в кодстайлах увидел что конец файла PHP надо так оформлять) Убрал

2022-09-24 13:05 UTC, Tazya approved these changes
Approved

2022-11-17 12:45 UTC, FishSev commented
задание выполнено

2022-11-17 12:45 UTC, closed without merging