выполняю задание 3
Kolesa-Education/kolesa-upgrade-homework-3 pull request #42
Opened 2022-09-25 14:18 UTC by Kudaiberdy

2022-09-25 14:53 UTC, lesmiras requested changes
Использовал микрофреймворк slim))
Это очень классно! Хороший инструмент для работы.
Но хотелось чтобы для начало обходился без готовых решений.

1) Основу slim с роутерами можно оставить, но попробуй сам реализовать без DI контейнеров, создавать экземпляр CatApiClient. 
2) Можно добавить еще классов для категории и изображения.
3) Добавь обработку ошибок запросов в API и вывести дружелюбный текст ошибки.

2022-09-25 14:53 UTC, lesmiras commented on public/index.php
> +    return $this->get('renderer')->render($response, 'index.phtml', $params);
В шаблоне требуется пременная $category, у меня выводится ошибка. Хотя в параметрах оно не передается.

2022-09-25 14:53 UTC, lesmiras commented on resources/templates/index.phtml
> +    <? require_once 'categories.phtml'?>
У меня не выводится список категорий.
Все ли корректно работает тут?

2022-09-25 14:53 UTC, lesmiras commented on app/CatApiClient.php
> +        return isset($params) ? $params[0]['url'] : 'service is not available';
Стоит на все запросы в API добавить try catch с обработкой ошибки.

2022-09-25 14:53 UTC, lesmiras commented on app/CatApiClient.php
> +    public function getCategoryCatsImg(): array|string
метод не возвращает изображения
а название чутка путает

2022-09-25 16:25 UTC, Kudaiberdy commented on public/index.php
> +    return $this->get('renderer')->render($response, 'index.phtml', $params);
Просто из задания подумал что будут использовать какие-то роуты, и соответственно нужен роутер, напились свой конечно можно было, но было бы еще кривее и горадо дольше, а так же так как уже имел дело со slim-ом то и мой выбор пал на него, да и к томуже он доповльно простой и легковесный. 
1. Окей, тогда попробую создавать классы снаружи роутов и передавать их через замыкание.
2. Вы имеете ввиду тип изображения(png/gif и прочее) или категории которые возвращает catapi, просто там категорий много категорий возвращается, и на сколько я понял переодически добавляются новые категоии фотографий с котами. И поэтому если добавится новая категория и если на нее не создать класс, то могет чегонибудь поломаться, ну или просто изображение может не вывозиться. Поэтому тут точно не знаю как лучше подойти.
3. Тут сделаю. И еще такой вопрос корректно ли будет возвращать 404 и сопутствующий текст(типо сервис временно не доступе)

2022-09-25 16:32 UTC, Kudaiberdy commented on resources/templates/index.phtml
> +    <? require_once 'categories.phtml'?>
очень странно, как обычно водиться, но у меня вроде все корректно работает. Не знаю конечно маловероятно что это связано с веб сервером, но я попробовал и на nginx и на встроенном в PHP веб сервере. Потыкаю еще попробую разобраться в чем проблема. И такой вопрос не загружажтся только категории, но картински с котиками загружаются? или вообще все падает?

2022-09-25 16:32 UTC, Kudaiberdy commented on app/CatApiClient.php
> +        return isset($params) ? $params[0]['url'] : 'service is not available';
тут соглан, поправлю

2022-09-25 16:38 UTC, Kudaiberdy commented on app/CatApiClient.php
> +    public function getCategoryCatsImg(): array|string
Ну да, этот метод и не возвращает изображения, а запрашивает у api список категорий, с названием и ключём по которому соответственно и происходит запрос к api через метод getCatImgByCategory(), который уже в свою очередь возвращает картинку в соответствии с переданной категорией.
А на счет имени матода, то согласен - путает. Придумаю более вменяемое название. Думаю getCategories() - будет нормально.

2022-09-25 16:51 UTC, Kudaiberdy commented on public/index.php
> +    return $this->get('renderer')->render($response, 'index.phtml', $params);
а да на счет этой "магической переменной", тут поидеи тоже затупил, она по идеи берется из друго шаблона, но сути это не меняет - получилось совсем не очень, и есть вариант как это поправить

2022-09-26 04:48 UTC, lesmiras commented on resources/templates/index.phtml
> +    <? require_once 'categories.phtml'?>
у меня строка `<? require_once 'categories.phtml'?>` как комментарий в исходном коде выводится

2022-09-26 13:34 UTC, lesmiras approved these changes

2022-09-26 13:34 UTC, lesmiras commented on app/CatApiClient.php
> +    public function getURLImageByCategory(string $categoryID): string
Могу посоветовать именовать методы так:
getImageUrlByRand
getImageUrlByCategory

Именование переменных и методов это отдельная история, не всегда удается дать четкое название))

2022-09-26 13:34 UTC, lesmiras commented on app/CatApiClient.php
> +            return '';
Обработка всех запросов, отлично! 
Но при обработке лучше возвращать кастомную ошибку. При возвращений строки не понятно что это ошибка, а может url нет. 

Попробуй тут вернуть какую нибудь ошибку со своим текстом и обработать его в роуте, ну и вывести его пользователю.

2022-09-26 13:34 UTC, lesmiras commented on app/CatApiClient.php
> +        return $params[0]['url'] ?? '';
Вот для результата запроса можно создать какой нибудь объект и дальше работать с ним. 
К примеру,
1) создать класс CatImage с свойствами id и url
2) результат запроса оформить в объект класса CatImage
3) вернуть этот объект
4) и в шаблоне работать с объектом, можно будет получать $catImage->id и $catImage->url

2022-09-26 14:09 UTC, Kudaiberdy commented on app/CatApiClient.php
> +            return '';
так и думал что на это внимание обратите, так как поведение не явным становится из за того что возвращается пустая строка. В это случае вместо возврата пустой строки нужно будет возвращать экземляр ошибки, а в роуте проверять возвращается ли ошибка?

2022-09-26 14:14 UTC, Kudaiberdy commented on app/CatApiClient.php
> +    public function getURLImageByCategory(string $categoryID): string
Пряното, поправлю.
На счет именования методов согласен. А еще на сколько я знаю - методы нужно именовать как глаголы(почти всегда), тоесть они не должны быть именами существительными, ну и соответственно именовать их нужно по тому действию которое 
они выполняют.

2022-09-26 14:35 UTC, Kudaiberdy commented on app/CatApiClient.php
> +        return $params[0]['url'] ?? '';
Тоесть по сути текущий класс CatApiClient будет выступать в роли некой фабрики? Хотя если рассмотреть расширение в дальнейшем, и будут появляться новые классы имеджей(к примеру DogImage или что нибудь такое), то навеное будет лучше уже создать какую нибудь фабрику отдельно, и передавать в эту фабрику полученный урл от экземляра класса CatApiClient(ну и соответственно класс переименовать AnimalImageApiClient) , а по этому урлу фабрика внутри сама будет диспетчерезировать классы по полученному урлу, и возвращать соответствующий объект. Ну и тут навероне нужно будет еще создать какойнибудь базовый класс для имеджей, что то вроде AnimalImage. Ну вот какое то такое решение появилось, хотя возможно я снова ушел в оверинженеринг?
Но перво-наперво по вашему комментарию, реализую класс CatImage и пока буду его возвращать из класса CatApiClient, по крайней мере на сколько я понял нужно так сделать

2022-09-26 14:38 UTC, Kudaiberdy commented on resources/templates/index.phtml
> +    <? require_once 'categories.phtml'?>
что-то не могу понять, эта строчка кода не работает? или она помечена как комментарий? Как-то странно получается. И в целом проект у вас на локальной машине завелся? или с ошибками падает?

2022-09-27 12:35 UTC, lesmiras commented on app/CatApiClient.php
> +            return '';
Ага)
Ну или тут хотя бы null возвращать, чтобы было понимание что ответ пустой, а не пустая строка

2022-09-27 12:36 UTC, lesmiras commented on resources/templates/index.phtml
> +    <? require_once 'categories.phtml'?>
Помечена как комментарий) 
Я не стал сильно исследовать проблему, вполне возможно что версий php или еще что отличается.

2022-09-27 12:39 UTC, closed without merging

2022-09-27 14:55 UTC, Kudaiberdy commented on resources/templates/index.phtml
> +    <? require_once 'categories.phtml'?>
Хм, ну у меня верия php 8.1, а у вас какая версия? А так же проверил коммиты, и вроде ни в каком из коммитов данная строка не была запомментирована, и все же мне интересно разобраться в чем же проблема)